### ISSUE TITLE
Run CCXCon as a production app

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ccxcon#10]
Make sure logging works properly
Make everything environment-variable-friendly

**Comment by noisecapella** [comment]
There's a `setup.py` file here, do we want to keep it? If so we need to make sure we keep its version number updated

**Comment by bdero** [comment]
I just setup a Heroku pipeline with `ccxcon-ci`, `ccxcon-rc`, and `ccxcon`, which now have automatic deployments mapped to `master`, `release-candidate`, and `release` respectively.

My next goal is to get automatic deployment working to a "review" branch (dependent on #18, #25, and #26), which I've enabled.

Once that works, we can:
- [ ] 1. Review and merge `feature/bdero/heroku` to `master`, which will trigger a deployment on `ccxcon-ci` as soon as tests pass on Travis.

And then follow a release process:
- [ ] 2. Begin our first pre-release (0.0.1) by creating `rc/0.0.1` on `master` and merging to `release-candidate`, which will trigger a deployment on `ccxcon-rc` after tests pass.
- [ ] 3. Generate release notes, create a PR from `release-candidate` to `release`, and verify changes for the release on `ccxcon-rc`.
- [ ] 4. And finally, trigger our first production pre-release by merging.

**Comment by justinabrahms** [comment]
What else is left for this? Can I help?
