### ISSUE TITLE
The course structure should not contain hidden elements

### ISSUE THREAD

**Issue by giocalitri** [mitodl/ccxcon#102]
Verify that the API used to pull the course structure from ex-platform does not return hidden modules.

**Comment by justinabrahms** [comment]
![image](https://cloud.githubusercontent.com/assets/3853/12327232/4370e7c4-baa3-11e5-9b77-ac0cfb26620c.png)

It looks like the answer is "requests made by staff do include hidden fields". See [here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/course_blocks/transformers/visibility.py)

**Comment by giocalitri** [comment]
I guess the only thing remaining is to verify on a local instance: I'll take care of this

**Comment by pdpinch** [comment]
add field to get_course_components API

**Comment by noisecapella** [comment]
I added it to the course blocks API: https://github.com/mitocw/edx-platform/pull/210
