### ISSUE TITLE
Fixture with test data that looks real

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#107]
Use Saif's 8.05x course

**Comment by justinabrahms** [comment]
I don't think this is going to be particularly exciting from a module listing perspective. Any other thoughts?

![image](https://cloud.githubusercontent.com/assets/3853/12432677/9ef51b80-beca-11e5-91f0-ce231d02cecd.png)

**Comment by pdpinch** [comment]
Well, that's disappointing. 

How about https://github.mit.edu/edX-Archives/edX-Archive-8.MechCx-1T2015

I don't have access to the course on edge, but I'm guessing the repo may be more helpful anyway? Let me know.
