### ISSUE TITLE
edx liveness

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/ccxcon#124]
We should have a field on the ccxcon model which represents whether the course is live on edx. Without this, we list courses that aren't active on edx, which means someone could buy them via teacher's portal.

Once we have this flag and it's being pulled in from edx, we should restrict listing views to only courses that are marked as edx_published.

**Comment by pdpinch** [comment]
As far as I know, edX doesn't have an active/inactive flag on courses. (Master) courses have end dates and enrollment end dates, but CCXs can (and should) still be created from them. 

I agree that we need a way to remove courses from the Teacher's Portal catalog, but I don't think we can infer that from edX.
