### ISSUE TITLE
set up ccxcon to work with edx-stage and teachersportal-rc

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#126]
@giocalitri @justinabrahms can you review and update this checklist? (remove this question when done)
- [ ] do a release that includes 0fe2da1 and take it at least as far as ccxcon-rc
- [x] create a user and oauth application in ccxcon for each edx instance we'll want to speak to
  - [x] For ccxcon-ci and ccxcon-rc this is exactly stage.edx.org
- [x] create a backing_instance model for that user, which contains the oauth information for the edx instance that will use this key
- [x] ccxcon objects on the edx instances we want to talk with (i.e. stage.edx.org)
- [ ] oauth applications & grants on the edx instances we want to talk with (i.e. stage.edx.org) 

Repeat this checklist when we want the chain to work in production, but in that case we'll want edx.org and edge.edx.org

**Comment by justinabrahms** [comment]
There will need to be:
- a user + oauth application for each edx instance we'll want to speak with
- a backing_instance model for that user, which contains the oauth information for the edx instance that will use this key
- ccxcon objects on the edx instances we want to talk with
- oauth applications & grants on the edx instances we want to talk with.

**Comment by pdpinch** [comment]
I updated the description to merge my list and Justin's.

**Comment by pdpinch** [comment]
I think we finally got the accounts and grants together. Giovanni, please close when you confirm. 

username: ccx_con_stage
e-mail: devops+ccx-connector-stage-user@edx.org

username: ccx-con-prod
e-mail: ccx-con-prod@edx.org

username: ccx-con-edge
e-mail: ccx-con-edge@edx.org

**Comment by giocalitri** [comment]
if this issue is only about ccxcon-rc and edx-stage, then it is complete.

if it has to include production, then we need to wait for the release of ccxcon
