### ISSUE TITLE
CCXcon production release 0.2.0

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#132]
We'd like to use the CCXcon to create a CCX for the User Innovation course. 

An issue is that we have a dependency (at least for testing) on Teacher's Portal. 
- [x] verify commits on ccxcon-rc
- [x] database update (maybe not necessary?)
- [x] configure edX oauth user & secret

**Comment by pdpinch** [comment]
@giocalitri you took care of the last checkbox on this today, right?

**Comment by giocalitri** [comment]
Yes, I did

Sent by my iDevice. May be rife with typos or poor judgment.

On Mar 1, 2016, at 6:49 PM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:

@giocalitrihttps://github.com/giocalitri you took care of the last checkbox on this today, right?
