### ISSUE TITLE
write a script to manually create a CCX via CCXCon

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#133]
... using the CCXCon API

specifically for the user innovation course, may also be the start of B2B creation of CCXs

**Comment by giocalitri** [comment]
should this script be self contained (no dependencies on the CCXCon code)?

**Comment by justinabrahms** [comment]
Yes, please. You can keep the same requirements file though. :)

On Tue, Feb 16, 2016 at 2:25 PM, Giovanni Di Milia <notifications@github.com
