### ISSUE TITLE
Initial pre-release

### ISSUE THREAD

**Issue by bdero** [mitodl/ccxcon#38]
The initial pre-release `rc/0.0.0` should work out any kinks in our release process and open the road for all of our future releases.

We should add in some release process documentation and adhere to that, similar to lore. Thoughts @pwilkins ?

Subtask of #10

**Comment by pdpinch** [comment]
Release process documentation was added in #41 

@bdero what's the status of this issue?

**Comment by pwilkins** [comment]
In #41 I added the LORE release documentation, substituting "ccxcon" for "LORE".  It is otherwise unchanged.

**Comment by pdpinch** [comment]
@bdero I think this is done?
