### ISSUE TITLE
More automated release process.

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/ccxcon#43]
We should have an automated release process. It should handle all the steps until we get to a PR for the release branch. From there, users will review and test as necessary. When that PR is merged, the build happens without further intervention.

**Comment by Ferdi** [comment]
Maybe our DevOps team can look into this. It applies to other projects as well

**Comment by pdpinch** [comment]
remaining work 
- [ ] push to release-candidate branch to start automatic deploy
- [ ] build PR to release

**Comment by bdero** [comment]
This might work for making the PR with hub (untested): `hub pull-request -b release-candidate -h "rc/[semver]" -m "[checklist template output]"`

**Comment by pwilkins** [comment]
The release script repository is here: https://github.com/mitodl/release-script

**Comment by pdpinch** [comment]
@pwilkins can we close this?

**Comment by pwilkins** [comment]
@pdpinch Best check with Justin.  The script itself is incomplete.  The last time I spoke with Justin he said that he was reconsidering the approach we're taking.

**Comment by pwilkins** [comment]
We used the release script to release 0.3.0, so I this can be closed.
