### ISSUE TITLE
application authentication with edX

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#5]
oAuth2

**Comment by pdpinch** [comment]
What's the status on this? I don't know why the PR was closed without merging.

**Comment by justinabrahms** [comment]
That PR was for a different ticket all together (teachersportal <-> ccxcon auth). "application edx auth" stuff is us communicating with edx over some trusted channel. I think we agreed that we could do one of two mechanisms, an oauth client or a shared secret. This can be moved forward, as long as @giocalitri's ccx work will be exposed via that authentication mechanism.

**Comment by pdpinch** [comment]
I think this is a duplicate of #158 ?
