### ISSUE TITLE
Django 1.9 changes

### ISSUE THREAD

**Issue by bdero** [mitodl/ccxcon#51]
Let's keep track of things that can affect the code base when moving to 1.9.

Here's one:
- We should remove the django.request config when we upgrade: https://docs.djangoproject.com/en/1.9/releases/1.9/#changes-to-the-default-logging-configuration (thanks for spotting @justinabrahms)

**Comment by pdpinch** [comment]
So keeping track of issues went right to upgrading? Is there user value to this upgrade?

**Comment by justinabrahms** [comment]
There are things that make django 1.9 nicer. `self.client.force_login` in testing, `self.client.json` being two in particular.
