### ISSUE TITLE
Support for querying specific item ids

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/ccxcon#63]
We currently only have support for fetching individual records or all the records. We should have a filtering mechanism in place, which will be used by TP to get a list of courses to display that are purchasable.

**Comment by jamiefolsom** [comment]
Yes, and I would imagine we're going to want to be able to support filtering by other criteria as well: topic, level, date published, author, institution, etc.

**Comment by pdpinch** [comment]
Is this issue still open?

@jamiefolsom @noisecapella

**Comment by noisecapella** [comment]
I think since we're controlling the filtering of what's purchasable in the teacher's portal, we don't need this issue anymore.

**Comment by pdpinch** [comment]
closing this
