### ISSUE TITLE
changes for POST to /api/v1/coursexs/

### ISSUE THREAD

**Issue by giocalitri** [mitodl/ccxcon#70]
Some changes are needed for POST requests to the endpoint `/api/v1/coursexs/`
- `image_url` needs to support just a path
- `edx_instance` should not be provided by the client
- `author_name` should accept `null` values
- `course_id` needs to be added to the list of fields: `course_id` is a string representation of a course locator on EDX and it is unique

**Comment by justinabrahms** [comment]
edx_instance not provided by client is fixed by #58

**Comment by justinabrahms** [comment]
Waiting on https://github.com/mitodl/ccxcon/pull/74
